#include <nova/syscall.h>
#include <nova/console.h>
#include <nova/mm/paging.h>
static volatile bool exit_seen, getpid_seen, write_seen, unknown_seen, badptr_seen, vfs_open_seen, vfs_read_seen, vfs_close_seen;
static bool valid_user(uint64_t p,uint64_t n){if(!n||p>0x00007fffffffffffULL||n>0x1000||p>0x00007fffffffffffULL-n)return false;for(uint64_t x=p&~0xfffULL,end=p+n;x<end;x+=0x1000){uint64_t pa;if(!paging_translate(x,&pa))return false;}return true;}
static uint64_t user_strlen(uint64_t p){if(!p||p>0x00007fffffffffffULL)return 0;for(uint64_t i=0;i<NOVA_VFS_MAX_PATH;i++){uint64_t page=p+i,pa;page&=~0xfffULL;if(i==0||((p+i)&0xfffULL)==0){if(!paging_translate(page,&pa))return 0;}if(((uint8_t*)(uintptr_t)(p+i))[0]==0)return i;}return 0;}
int64_t syscall_dispatch(uint64_t n,uint64_t a1,uint64_t a2,uint64_t a3){uint64_t len;switch(n){case NOVA_SYS_GETPID:getpid_seen=true;return 1;case NOVA_SYS_WRITE:if(!valid_user(a2,a3)){badptr_seen=true;return NOVA_SYS_EFAULT;}if(a1==1){for(len=0;len<a3;len++)console_putchar(((const char*)(uintptr_t)a2)[len]);write_seen=true;return (int64_t)a3;}return vfs_write((int64_t)a1,(const void*)(uintptr_t)a2,a3);case NOVA_SYS_EXIT:exit_seen=true;return 0;case NOVA_SYS_OPEN:if(!user_strlen(a1))return NOVA_SYS_EFAULT;vfs_open_seen=true;return vfs_open((const char*)(uintptr_t)a1);case NOVA_SYS_CLOSE:if(vfs_close((int64_t)a1)!=0)return NOVA_SYS_EBADF;vfs_close_seen=true;return 0;case NOVA_SYS_READ:if(!valid_user(a2,a3))return NOVA_SYS_EFAULT;vfs_read_seen=true;return vfs_read((int64_t)a1,(void*)(uintptr_t)a2,a3);case NOVA_SYS_LSEEK:return vfs_seek((int64_t)a1,a2);case NOVA_SYS_STAT:if(!valid_user(a2,sizeof(struct nova_stat)))return NOVA_SYS_EFAULT;if(!vfs_stat((int64_t)a1,(struct nova_stat*)(uintptr_t)a2))return NOVA_SYS_EBADF;return 0;default:unknown_seen=true;return NOVA_SYS_ENOSYS;}}
void syscall_interrupt(uint64_t *s){s[0]=(uint64_t)syscall_dispatch(s[0],s[6],s[5],s[2]);}
bool syscall_exit_seen(void){return exit_seen;}
bool syscall_self_test(void){ console_printf("[NovaOS] syscall flags pid=%x write=%x unknown=%x badptr=%x exit=%x open=%x read=%x close=%x\n",getpid_seen,write_seen,unknown_seen,badptr_seen,exit_seen,vfs_open_seen,vfs_read_seen,vfs_close_seen); return getpid_seen&&write_seen&&unknown_seen&&badptr_seen&&exit_seen&&vfs_open_seen&&vfs_read_seen&&vfs_close_seen;}
